version: '3'

networks:
    webapp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        links:
            - app
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - webapp
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - "9001:9000"
            - "6001:6001"
        networks:
            - webapp
